In [15]:
import glob
import os
import numpy as np
import cv2
import imutils
import math
from scipy import misc

In [16]:
img = [[0,0,0,0,0],
      [0,0,1,1,0],
      [0,1,1,1,0],
      [0,1,1,1,1],
      [0,0,1,1,1],
      [0,0,0,0,0]]
img = np.array(img)

In [17]:
oneValue = np.argwhere(img==1)[0]
r = oneValue[0]
c = oneValue[1]
# r = 2
# c = 1
ctrImg = np.zeros(img.shape)
ctrImg[r,c] = 1
coor = [r,c]
startCoor = [r,c]
print(ctrImg)
print(coor)

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
[1, 2]


In [18]:
maksCoorR, maksCoorC = img.shape
coorHalfWrist = [maksCoorR, maksCoorC/2]
posisi =[]
print(coorHalfWrist)

[6, 2.5]


In [19]:
newCoor = [0,0]
coorDis = []
direction = []
dire = 7
indikator = 1
# print(coor)
count = 0
counts = 0
while indikator == 1:
    counts += 1
#     print(count)
    if dire % 2 == 0:
        startDir = (dire+7) % 8
    else:
        startDir = (dire+6) % 8
    currentDir = startDir
    for i in range(8):
        if currentDir == 8:
            currentDir = 0
        if currentDir == 0:
            posisi = [0, 1]
        elif currentDir == 1:
            posisi = [-1, 1]
        elif currentDir == 2:
            posisi = [-1, 0]
        elif currentDir == 3:
            posisi = [-1, -1]
        elif currentDir == 4:
            posisi = [0, -1]
        elif currentDir == 5:
            posisi = [1, -1]
        elif currentDir == 6:
            posisi = [1, 0]
        elif currentDir == 7:
            posisi = [1, 1]
        dire = currentDir
#         print("posisi")
#         print(posisi)
#         print("coor")
#         print(coor)
        newCoor[0] = coor[0] + posisi[0]
        newCoor[1] = coor[1] + posisi[1]
#         print("newCoor")
#         print(newCoor)
        if newCoor[0] >= 0 and newCoor[1] >= 0 and newCoor[0] < maksCoorR-1 and newCoor[1] < maksCoorC-1:
            if img[newCoor[0], newCoor[1]] == 1:
                ctrImg[newCoor[0], newCoor[1]] = 1
                coor[0] = newCoor[0]
                coor[1] = newCoor[1]
#                 print(newCoor)
                a = math.pow((newCoor[0] - coorHalfWrist[0] + 1),2)
                b = math.pow((newCoor[1] - coorHalfWrist[1] + 1),2)
                c = a + b
#                 print(c)
                distances = math.sqrt(c)
                coorDis.append([])
                direction.append([])
                coorDis[count].append(newCoor[0])
                coorDis[count].append(newCoor[1])
                coorDis[count].append(distances)
                direction[count].append(dire)
                count += 1
                break
            else:
                currentDir += 1
        else:
            currentDir += 1
    if startCoor == coor:
        indikator = 0

In [20]:
count

8

In [21]:
coorDis

[[2, 1, 3.0413812651491097],
 [3, 1, 2.0615528128088303],
 [4, 2, 1.118033988749895],
 [4, 3, 1.8027756377319946],
 [3, 3, 2.5],
 [2, 3, 3.3541019662496847],
 [1, 3, 4.272001872658765],
 [1, 2, 4.031128874149275]]

In [22]:
ctrImg

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.],
       [ 0.,  0.,  1.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [23]:
# Distance Distribution Diagram
sumbuX = []
sumbuX = np.arange(len(coorDis))
sumbuX = np.array(sumbuX)
minDistance = np.amin(coorDis, axis =0)[2]
indexDistance = np.argwhere(coorDis == minDistance)
r = indexDistance[0][0]
c = 0
print(indexDistance)

[[2 2]]


In [24]:
print(coorDis)
print(type(coorDis))

[[2, 1, 3.0413812651491097], [3, 1, 2.0615528128088303], [4, 2, 1.118033988749895], [4, 3, 1.8027756377319946], [3, 3, 2.5], [2, 3, 3.3541019662496847], [1, 3, 4.272001872658765], [1, 2, 4.031128874149275]]
<class 'list'>


In [25]:
newCoorDis = []
for i in range(len(coorDis) - r):
    newCoorDis.append(coorDis[i+r])
for i in range(r):
    newCoorDis.append(coorDis[i])
newCoorDis = np.array(newCoorDis)
print(newCoorDis)
print(type(newCoorDis))

[[ 4.          2.          1.11803399]
 [ 4.          3.          1.80277564]
 [ 3.          3.          2.5       ]
 [ 2.          3.          3.35410197]
 [ 1.          3.          4.27200187]
 [ 1.          2.          4.03112887]
 [ 2.          1.          3.04138127]
 [ 3.          1.          2.06155281]]
<class 'numpy.ndarray'>


In [26]:
zeroDis = float(1)
r = []
c = []
for i in range(len(newCoorDis)):
    if newCoorDis[i][0] > zeroDis:
        newCoorDis[i][2] = 0
print(newCoorDis)
distancess = []
for i in range(len(newCoorDis)):
    distancess.append(newCoorDis[i][2])
distancess = np.array(distancess)
print(distancess)

[[ 4.          2.          0.        ]
 [ 4.          3.          0.        ]
 [ 3.          3.          0.        ]
 [ 2.          3.          0.        ]
 [ 1.          3.          4.27200187]
 [ 1.          2.          4.03112887]
 [ 2.          1.          0.        ]
 [ 3.          1.          0.        ]]
[ 0.          0.          0.          0.          4.27200187  4.03112887
  0.          0.        ]


In [62]:
def getPeak(Data, i, s):
    if (i-s) < 1:
        top = 0
    else:
        top = i - s - 1
    y = Data[1]
#     print(len(y))
    if (i+s) > len(y):
        bottom = len(y) - 1
    else:
        bottom = i + s - 1
    p = []
#     print(top)
#     print(bottom)
    if y[i] == max(y[top:bottom]) or y[i] == min(y[top:bottom]):
        p = [Data[0][i], Data[1][i]]
    else:
        p.append(float('nan'))
        p.append(float('nan'))
    return p

In [68]:
def fpeak(sumbuX, distancess, sensitivityFunc):
    rx = len(sumbuX)
    ry = len(newCoorDis)
    sensitivityFunc = []
    sensitivityFunc.append(3)
    if sensitivityFunc[0] == 0:
        sensitivityFunc[0] = 1
#     print(rx)
    Data = np.vstack((sumbuX, distancess))
    output = []
    for i in range(rx):
        isP = getPeak(Data, i, sensitivityFunc[0])
#         print(isP)
        if np.isnan(isP).sum() == 0:
            output.append(isP)
    return output

In [69]:
output = fpeak(sumbuX, distancess, sensitivityFunc)
print(output)
for i in range(len(output)):
    if i == len(output) - 1:
        output[i].append(0)
        break
    if output[i][1] == output[i+1][1]:
        output[i].append(1)
    else:
        output[i].append(0)
print(output)

0
2
0
3
0
4
0
5
0
6
1
7
2
7
3
7
[[0.0, 0.0], [1.0, 0.0], [2.0, 0.0], [3.0, 0.0], [4.0, 4.2720018726587652], [6.0, 0.0], [7.0, 0.0]]
[[0.0, 0.0, 1], [1.0, 0.0, 1], [2.0, 0.0, 1], [3.0, 0.0, 0], [4.0, 4.2720018726587652, 0], [6.0, 0.0, 1], [7.0, 0.0, 0]]


In [32]:
outpuT = []
for i in output:
    if i[2] == float(0):
        outpuT.append(i)
print(outpuT)

[[3.0, 0.0, 0], [4.0, 4.2720018726587652, 0], [7.0, 0.0, 0]]


In [33]:
print(outpuT)
pixelP1 = outpuT[0][0]
pixelP2 = outpuT[2][0]
print(pixelP1)
coorP1 = []
coorP2 = []
coorP1 = [newCoorDis[int(pixelP1)][0], newCoorDis[int(pixelP1)][1]]
coorP2 = [newCoorDis[int(pixelP2)][0], newCoorDis[int(pixelP2)][1]]
print(coorP1)
print(pixelP2)
print(coorP2)

[[3.0, 0.0, 0], [4.0, 4.2720018726587652, 0], [7.0, 0.0, 0]]
3.0
[2.0, 3.0]
7.0
[3.0, 1.0]


In [34]:
# kemiringan p1 dam p2
temp = (coorP2[1] - coorP1[1]) / (coorP2[0] - coorP1[0])
rad = math.atan(temp) / math.pi * 180
print(rad)

-63.43494882292201


In [35]:
newImg = misc.imrotate(img,40,interp='bilinear')
print(newImg)

[[  0   0  58   0   0]
 [  7 180 255  68 162]
 [  0 195 255 249 255]
 [ 22 232 255 255 212]
 [  0  68  95 144  16]
 [  0   0   0   0   0]]


In [36]:
temp = np.zeros_like(img)
temp[int(coorP1[0])][int(coorP1[1])] = 1
temp[int(coorP2[0])][int(coorP2[1])] = 1
print(temp)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 1 0]
 [0 1 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [37]:
tempRotate = misc.imrotate(temp,40,interp='bilinear')
print(tempRotate)

[[ 0  0  0  0  0]
 [ 0  0 86 68  0]
 [ 0  0 72 55  0]
 [ 0 55 72  0  0]
 [ 0 68 86  0  0]
 [ 0  0  0  0  0]]


In [38]:
tempIndex = np.argwhere(tempRotate>0)
print(tempIndex)

[[1 2]
 [1 3]
 [2 2]
 [2 3]
 [3 1]
 [3 2]
 [4 1]
 [4 2]]


In [70]:
newCoorP1 = [tempIndex[0][0], tempIndex[0][1]]
newCoorP2 = [tempIndex[len(tempIndex)-1][0], tempIndex[len(tempIndex)-1][1]]
print(newCoorP1)
print(newCoorP2)

[1, 2]
[4, 2]


In [72]:
a = math.pow((newCoorP1[0]-newCoorP2[0]),2)
b = math.pow((newCoorP1[1]-newCoorP2[1]),2)
distance = math.sqrt(a+b)
print(distance)
# ROI output
print(int(newCoorP1[0]-distance))
print(int(newCoorP1[1]-distance))
fiturI = img[int(newCoorP1[0]):int(newCoorP1[0]+distance), int(newCoorP1[1]):int(newCoorP1[1]+distance)]
print(fiturI)

3.0
-2
-1
[[1 1 0]
 [1 1 0]
 [1 1 1]]
